# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import login_page_res
import authenticate

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 400)
        Form.setObjectName("Form")
        Form.resize(400, 400)
        Form.setWindowFlags(QtCore.Qt.CustomizeWindowHint | QtCore.Qt.FramelessWindowHint | QtCore.Qt.Tool);
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground);
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(400, 400))
        Form.setMaximumSize(QtCore.QSize(400, 600))
        Form.setStyleSheet("*{\n"
"    color:white;\n"
"}\n"
"#profile_banner_container{\n"
"    background-color: #02254d;\n"
"    border:none;\n"
"    border-radius:60px;\n"
"}\n"
"#login_btn_container{\n"
"background-color: rgba(162, 179, 205, 150);\n"
"border-bottom-left-radius: 20px;\n"
"border-bottom-right-radius: 20px;\n"
"}\n"
"#login_input_container{\n"
"background-color: rgba(162, 179, 205, 150);\n"
"    border-radius:20px;\n"
"}\n"
"#login_input{\n"
"    color:white;\n"
"    border:none;\n"
"    background-color: rgb(57, 81, 115);\n"
"}\n"
"#user_icon,#exit_icon{\n"
"    color:white;\n"
"    background-color: #00254f;\n"
"    border:none;\n"
"}\n"
"#exit_icon{\n"
"    border-bottom-left-radius: 20px;\n"
"}\n"
"#login_button{\n"
"    background:none;\n"
"    border:none;\n"
"}\n"
"#login_button:hover{\n"
"    color:#02254d;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.login_form_container = QtWidgets.QWidget(Form)
        self.login_form_container.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_form_container.sizePolicy().hasHeightForWidth())
        self.login_form_container.setSizePolicy(sizePolicy)
        self.login_form_container.setMinimumSize(QtCore.QSize(400, 400))
        self.login_form_container.setObjectName("login_form_container")
        self.login_input_container = QtWidgets.QWidget(self.login_form_container)
        self.login_input_container.setGeometry(QtCore.QRect(20, 60, 360, 260))
        self.login_input_container.setObjectName("login_input_container")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.login_input_container)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(13, 140, 332, 62))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.user_icon = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.user_icon.sizePolicy().hasHeightForWidth())
        self.user_icon.setSizePolicy(sizePolicy)
        self.user_icon.setMinimumSize(QtCore.QSize(60, 60))
        self.user_icon.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        self.user_icon.setFont(font)
        self.user_icon.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/user.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.user_icon.setIcon(icon)
        self.user_icon.setIconSize(QtCore.QSize(32, 32))
        self.user_icon.setObjectName("user_icon")
        self.horizontalLayout.addWidget(self.user_icon)
        self.login_input = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(250)
        sizePolicy.setVerticalStretch(40)
        sizePolicy.setHeightForWidth(self.login_input.sizePolicy().hasHeightForWidth())
        self.login_input.setSizePolicy(sizePolicy)
        self.login_input.setMinimumSize(QtCore.QSize(270, 60))
        self.login_input.setMaximumSize(QtCore.QSize(270, 60))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        font.setPointSize(12)
        self.login_input.setFont(font)
        self.login_input.setText("")
        self.login_input.setObjectName("login_input")
        self.horizontalLayout.addWidget(self.login_input)
        self.label = QtWidgets.QLabel(self.login_input_container)
        self.label.setGeometry(QtCore.QRect(10, 90, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.exit_icon = QtWidgets.QPushButton(self.login_input_container,clicked= lambda: onExitListner())
        self.exit_icon.setGeometry(QtCore.QRect(300, 0, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exit_icon.sizePolicy().hasHeightForWidth())
        self.exit_icon.setSizePolicy(sizePolicy)
        self.exit_icon.setMinimumSize(QtCore.QSize(60, 60))
        self.exit_icon.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        self.exit_icon.setFont(font)
        self.exit_icon.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/exit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_icon.setIcon(icon1)
        self.exit_icon.setIconSize(QtCore.QSize(50, 50))
        self.exit_icon.setObjectName("exit_icon")
        self.profile_banner_container = QtWidgets.QPushButton(self.login_form_container)
        self.profile_banner_container.setGeometry(QtCore.QRect(141, 10, 120, 120))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profile_banner_container.sizePolicy().hasHeightForWidth())
        self.profile_banner_container.setSizePolicy(sizePolicy)
        self.profile_banner_container.setMinimumSize(QtCore.QSize(120, 120))
        self.profile_banner_container.setMaximumSize(QtCore.QSize(120, 120))
        self.profile_banner_container.setText("")
        self.profile_banner_container.setIcon(icon)
        self.profile_banner_container.setIconSize(QtCore.QSize(64, 64))
        self.profile_banner_container.setObjectName("profile_banner_container")
        self.login_btn_container = QtWidgets.QWidget(self.login_form_container)
        self.login_btn_container.setGeometry(QtCore.QRect(52, 320, 300, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_btn_container.sizePolicy().hasHeightForWidth())
        self.login_btn_container.setSizePolicy(sizePolicy)
        self.login_btn_container.setMinimumSize(QtCore.QSize(300, 50))
        self.login_btn_container.setMaximumSize(QtCore.QSize(300, 50))
        self.login_btn_container.setObjectName("login_btn_container")
        self.login_button = QtWidgets.QPushButton(self.login_btn_container,clicked= lambda: self.onLoginListner())
        self.login_button.setGeometry(QtCore.QRect(18, 2, 260, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.login_button.setFont(font)
        self.login_button.setObjectName("login_button")
        self.verticalLayout.addWidget(self.login_form_container)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def onLoginListner(self):
        userId = self.login_input.text()
        #checking if the user_id is valid to login
        if not authenticate.login(userId):
             self.label.setText("Invalid Credentials.")
        else: 
            self.label.setText("Logging In...")
        

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.login_input.setPlaceholderText(_translate("Form", "User ID"))
        self.label.setText(_translate("Form", "Enter your Yelp user ID:"))
        self.login_button.setText(_translate("Form", "LOG IN"))

def onExitListner():
    exit(0)


